### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by dcci** [rcorcs/llvm-heat-printer#1]
Hi,
I'm using this project and I like it a lot.
Couple of notes:
1) Maybe you can mention setting `-DLLVM_DIR=` in the instruction on how to install for people that don't have the libraries installed? (that's what I did to get it working).
2) You can also mention `-fprofile-generate/-fprofile-use` which enables IR-level instrumentation instead of FE-level instrumentation (the former, FWIW, it's much less intrusive and people prefer it nowadays).

Thanks!

--
Davide

**Comment by rcorcs** [comment]
Thanks for the suggestions!
I'm glad you like this project.
